name: New Extension Request
description: Suggest an idea for this project
labels: [new koala extension]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Our community needs to automate [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: A numbered list of clear and concise description of what you want to happen.
      placeholder: |
        1. Read command k!koala
        2. Send a random picture of a koala
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered, or examples of where something similar is implemented.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here, as well as the version of KoalaBot this affects.
    validations:
      required: false